### ISSUE TITLE
Unicode characters in README.rst breaks compilation with python-3.6

### ISSUE THREAD

**Issue by infracaninophile** [pydanny/whichcraft#10]
I've locally patched the FreeBSD port of py-whichcraft to avoid a compilation problem with python-3.6.x:

```
=======================<phase: configure      >============================
===>   py36-whichcraft-0.5.2 depends on package: py36-setuptools>0 - found
===>   py36-whichcraft-0.5.2 depends on file: /usr/local/bin/python3.6 - found
===>   py36-whichcraft-0.5.2 depends on file: /usr/local/bin/ccache - found
===>  Configuring for py36-whichcraft-0.5.2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 35, in <module>
    readme = open("README.rst").read()
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1067: ordinal not in range(128)
*** Error code 1

Stop.
```

Looks like some unicode characters sneaked into README.rst.   The patch is available here:

https://svnweb.freebsd.org/ports/head/devel/py-whichcraft/files/patch-README.rst?revision=481787&view=co

I'd just paste it into this report, but I doubt the subtleties of the whitespace changes would survive the process.

**Comment by ghost** [comment]
@infracaninophile I submitted a PR to fix this as I ran into it myself while doing some packaging of the module. I also fixed the new line at the end of the file which did not exist.
