### ISSUE TITLE
Please release new package w/correct whichcraft.__version__

### ISSUE THREAD

**Issue by userzimmermann** [pydanny/whichcraft#19]
Hi :)

I know, https://github.com/cookiecutter/whichcraft/commit/465d53208261a8248305268e518ff17000bfaa92 fixed the mismatch of `whichcraft.__version__`, but the https://pypi.org/project/whichcraft/0.6.0 release still contains the wrong `__version__ = "0.5.3"` line

And this breaks my custom generalized dependency checks that I do in most of my projects, so I need to do hacky workarounds for `whichcraft` as requirement ;) 

Can you please quickly make a new `0.6.1` release or so?

BTW, in case you don't know it: There is https://pypi.org/project/setuptools-scm , a nice official https://www.pypa.io tool for automatically determining project versions based on Git tags and passing them to `setup()` by using a simple setup entry point, also offering the feature of additionally writing the version into a Python module for keeping everything automatically consistent. I use it in all my Python projects, and even in some non-Python projects :)

Kind regards,
Stefan

**Comment by pydanny** [comment]
@userzimmermann I'm deploying a new version now. 

As for setuptools-scm, if you submit a PR I'll start using it. 😄

**Comment by pydanny** [comment]
@userzimmermann Published: https://pypi.org/project/whichcraft/0.6.1/
