### ISSUE TITLE
error on windows

### ISSUE THREAD

**Issue by eromoe** [pydanny/whichcraft#4]
E:\Project\whichcraft>python test_whichcraft.py
============================= test session starts =============================
platform win32 -- Python 2.7.10, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: E:\Project\whichcraft, inifile:
plugins: cov-2.2.1
collected 2 items

test_whichcraft.py F.

================================== FAILURES ===================================
____________________________ test_existing_command ____________________________

def test_existing_command():
    cmd = which('date')
  assert cmd
E assert None
test_whichcraft.py:9: AssertionError
===================== 1 failed, 1 passed in 0.17 seconds ======================

reference to https://github.com/audreyr/cookiecutter/issues/703

**Comment by pydanny** [comment]
I'm not certain that `date` is a Windows CLI command. Could you modify that test to try `echo` or another command that is certain to run on Windows?

**Comment by eromoe** [comment]
I add `dir`, fail too

```
================================== FAILURES ===================================
____________________________ test_existing_command ____________________________

    def test_existing_command():
        x = which('dir')
>       assert x
E       assert None

test_whichcraft.py:9: AssertionError
===================== 1 failed, 1 passed in 0.04 seconds ======================
```

**Comment by pydanny** [comment]
Which version of Windows are you on?

**Comment by eromoe** [comment]
win7 x64

**Comment by Shados** [comment]
@eromoe `dir` and `date` are _both_ DOS shell commands and are implemented internally to `cmd.exe`, they do not have external, stand-alone executable files.

**Comment by ofek** [comment]
@pydanny This can be closed.
